opt_config : { 
    type: adamw,
    lr: 0.0001,
    betas: [0.95, 0.999],
    eps: 0.000001,
    weight_decay: 0.001
}

sched_config : {
    type: linear,
    min_lr: 0.00001
}

dataset : {
  train : { _base_: cfgs/dataset_configs/RealSensor.yaml, 
            others: {subset: 'test'}},
  val : { _base_: cfgs/dataset_configs/RealSensor.yaml, 
            others: {subset: 'test'}},
  test : { _base_: cfgs/dataset_configs/RealSensor.yaml, 
            others: {subset: 'test'}} 
}
            
model : { 
    backbone_model : base40M-textvec,
    merge_mdoel : AdaPoinTr_head,
    partial_scale : 1.0,
    center_num : [512,256],
    k_knn : 16,
    partial_c: 512,
    use_low: False
}
  
total_bs : 48
step_per_update : 1
max_epoch : 300

consider_metric: CDL1
